version: '3.8'

services:
    dehack-backend:
        build: .
        ports:
            - "8080:8080"
        environment:
            - PORT=8080
            - FLASK_DEBUG=false
        volumes:
            - ./data:/app/data
            - ./uploads:/app/uploads
        healthcheck:
            test: ["CMD", "curl", "-f", "http://localhost:8080/"]
            interval: 30s
            timeout: 10s
            retries: 3
            start_period: 40s
        restart: unless-stopped
